// <auto-generated />
using System;
using CineTicket.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineTicket.Web.Migrations
{
    [DbContext(typeof(CineTicketContext))]
    partial class CineTicketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CineTicket.Web.Models.Asiento", b =>
                {
                    b.Property<int>("IdAsiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsiento"));

                    b.Property<string>("Fila")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int>("IdSala")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("IdAsiento")
                        .HasName("PK__Asientos__F5678721D0B785FF");

                    b.HasIndex("IdSala");

                    b.ToTable("Asientos");
                });

            modelBuilder.Entity("CineTicket.Web.Models.DetalleVentum", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("IdAsiento")
                        .HasColumnType("int");

                    b.Property<int>("IdFuncion")
                        .HasColumnType("int");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("IdDetalle")
                        .HasName("PK__DetalleV__E43646A5B0F56608");

                    b.HasIndex("IdAsiento");

                    b.HasIndex("IdFuncion");

                    b.HasIndex("IdVenta");

                    b.ToTable("DetalleVenta");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Funcione", b =>
                {
                    b.Property<int>("IdFuncion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuncion"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("IdPelicula")
                        .HasColumnType("int");

                    b.Property<int>("IdSala")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioEntrada")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("IdFuncion")
                        .HasName("PK__Funcione__7D4132883E33300A");

                    b.HasIndex("IdPelicula");

                    b.HasIndex("IdSala");

                    b.ToTable("Funciones");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGenero"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("IdGenero")
                        .HasName("PK__Generos__0F83498816E1D3E0");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Generos__75E3EFCF2E4AF571")
                        .IsUnique();

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Pelicula", b =>
                {
                    b.Property<int>("IdPelicula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPelicula"));

                    b.Property<string>("Clasificacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("DuracionMin")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdGenero")
                        .HasColumnType("int");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Sinopsis")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdPelicula")
                        .HasName("PK__Pelicula__60537FD0B402A86C");

                    b.HasIndex("IdGenero");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRol")
                        .HasName("PK__Roles__2A49584CD53478DA");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Sala", b =>
                {
                    b.Property<int>("IdSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSala"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("IdSala")
                        .HasName("PK__Salas__A04F9B3BE89125DA");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoReset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CodigoResetExpira")
                        .HasColumnType("datetime2");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuarios__5B65BF974C3CA82F");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "Correo" }, "UQ__Usuarios__60695A198DBF786E")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("CONFIRMADA");

                    b.Property<DateTime>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("IdVenta")
                        .HasName("PK__Ventas__BC1240BD7F9CFACC");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Asiento", b =>
                {
                    b.HasOne("CineTicket.Web.Models.Sala", "IdSalaNavigation")
                        .WithMany("Asientos")
                        .HasForeignKey("IdSala")
                        .IsRequired()
                        .HasConstraintName("FK__Asientos__IdSala__46E78A0C");

                    b.Navigation("IdSalaNavigation");
                });

            modelBuilder.Entity("CineTicket.Web.Models.DetalleVentum", b =>
                {
                    b.HasOne("CineTicket.Web.Models.Asiento", "IdAsientoNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdAsiento")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleVe__IdAsi__5441852A");

                    b.HasOne("CineTicket.Web.Models.Funcione", "IdFuncionNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdFuncion")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleVe__IdFun__534D60F1");

                    b.HasOne("CineTicket.Web.Models.Venta", "IdVentaNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdVenta")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleVe__IdVen__52593CB8");

                    b.Navigation("IdAsientoNavigation");

                    b.Navigation("IdFuncionNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Funcione", b =>
                {
                    b.HasOne("CineTicket.Web.Models.Pelicula", "IdPeliculaNavigation")
                        .WithMany("Funciones")
                        .HasForeignKey("IdPelicula")
                        .IsRequired()
                        .HasConstraintName("FK__Funciones__IdPel__49C3F6B7");

                    b.HasOne("CineTicket.Web.Models.Sala", "IdSalaNavigation")
                        .WithMany("Funciones")
                        .HasForeignKey("IdSala")
                        .IsRequired()
                        .HasConstraintName("FK__Funciones__IdSal__4AB81AF0");

                    b.Navigation("IdPeliculaNavigation");

                    b.Navigation("IdSalaNavigation");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Pelicula", b =>
                {
                    b.HasOne("CineTicket.Web.Models.Genero", "IdGeneroNavigation")
                        .WithMany("Peliculas")
                        .HasForeignKey("IdGenero")
                        .IsRequired()
                        .HasConstraintName("FK__Peliculas__IdGen__412EB0B6");

                    b.Navigation("IdGeneroNavigation");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Usuario", b =>
                {
                    b.HasOne("CineTicket.Web.Models.Role", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__Usuarios__IdRol__3A81B327");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Venta", b =>
                {
                    b.HasOne("CineTicket.Web.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__Ventas__IdUsuari__4D94879B");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Asiento", b =>
                {
                    b.Navigation("DetalleVenta");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Funcione", b =>
                {
                    b.Navigation("DetalleVenta");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Genero", b =>
                {
                    b.Navigation("Peliculas");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Pelicula", b =>
                {
                    b.Navigation("Funciones");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Sala", b =>
                {
                    b.Navigation("Asientos");

                    b.Navigation("Funciones");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Usuario", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("CineTicket.Web.Models.Venta", b =>
                {
                    b.Navigation("DetalleVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
